I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 359, in script
    с "{cps=60}Чё, ты кто, я тебя знаю, и вообще какое право ты имеешь разговаривать со мной, пока я обедаю, тебя что, родители вообще не учили манерам{/cps}"
Exception: Sayer 'с' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 359, in script
    с "{cps=60}Чё, ты кто, я тебя знаю, и вообще какое право ты имеешь разговаривать со мной, пока я обедаю, тебя что, родители вообще не учили манерам{/cps}"
  File "C:\Users\frogenf\Downloads\renpy-8.3.3-sdk.7z\renpy-8.3.3-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\frogenf\Downloads\renpy-8.3.3-sdk.7z\renpy-8.3.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\frogenf\Downloads\renpy-8.3.3-sdk.7z\renpy-8.3.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'с' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24111502
Бесконечность в КемГУ 0.1
Thu Dec  5 20:22:04 2024
